### PR TITLE
Monolog 3 Support

### PR DESCRIPTION
**Pull request by segrax**
Hi,

note: this is BC breaking due to the Monolog change, and should target a v2 release

- Add support for monolog3
- Set minimum php version to 8.1
- ~~Add remaining member/parameter/return types~~
- ~~Set BaseType to abstract & implement JsonSerializable~~
- ~~Remove redundant type declarations in comments~~
- ~~Update to Composer 2.5~~

### CODE REVIEW

**Comment by Nacoma** [comment]
Lack of monolog v3 support is blocking us from upgrading our systems. Is there an ETA for a new version that supports it?

**Comment by georgeconstantinou** [comment]
Same here, any plans of merging this MR and tagging a new release?

**Comment by sirantd** [comment]
Waiting for it as well

**Comment by SergeyKleyman** [comment]
@segrax First of all thank you very much for your contribution.

My main concern is dropping support for PHP versions before than 8.1. According to [the package stats at packagist.org](https://packagist.org/packages/elastic/ecs-logging/php-stats) more than 60% of downloads originate from PHP versions below 8.1.

Another concern I have about the PR (which is in a way related to the point above) is the fact that it tries to cover multiple goals. Can the items other than main one (Monolog 3 support) be covered in separate PRs?

It brings me to the following suggestion: if this PR could be limited to just the stated subject (Monolog 3 support) then merging it will become much easier task.

**Comment by segrax** [comment]
Hey @SergeyKleyman,

Sure! We can definitely do that. 

However, please be aware that the minimum requirement for Monolog 3.0.0 is PHP >= 8.1

**Comment by rexs123** [comment]
Waiting for this as well, holding us back from upgrading.

**Comment by segrax** [comment]
Hey @SergeyKleyman 

Other improvements have been removed, its now just required changes for Monolog3 support

**Comment by sirantd** [comment]
Can anyone take a look at this PR, waiting for it

**Comment by JoppeDC** [comment]
Can we get an update on this? :)

**Comment by njonchee** [comment]
We are currently waiting on this

**Comment by JoppeDC** [comment]
@SergeyKleyman Friendly ping ;)

**Comment by SergeyKleyman** [comment]
@segrax Thank you very much for your effort but after your latest changes the support for both PHP 7.2-80 and Monolog 2.* is dropped. According to Packagist both are still widely used.
One solution I see as possible at the moment is to change `ElasticCommonSchemaFormatter` in a way that can work with both Monolog 2 and 3.

**Comment by segrax** [comment]
@SergeyKleyman  Yes, that's right. However, we've assumed that since this library seldom undergoes changes, it wouldn't pose a significant problem. The older versions will remain accessible, and Composer will utilize them according to the PHP version being used.

**Review by intuibase — APPROVED** [review]

**Pull request merged**
